basePath: /v1
host: pixelrental-production.up.railway.app:8080
info:
  contact:
    email: ucokkocu411@gmail.com
    name: ucok-man
  description: Documentation for Transaction API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Transaction API
  version: "1.0"
paths: {}
swagger: "2.0"
